// Code generated by "stringer -type=fileType"; DO NOT EDIT.

package qbecc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fileTypeInvalid-0]
	_ = x[fileTypeC-1]
	_ = x[fileTypeH-2]
	_ = x[fileTypeELF-3]
	_ = x[fileTypeHostAsm-4]
	_ = x[fileTypeQbeSSA-5]
}

const _fileType_name = "fileTypeInvalidfileTypeCfileTypeHfileTypeELFfileTypeHostAsmfileTypeQbeSSA"

var _fileType_index = [...]uint8{0, 15, 24, 33, 44, 59, 73}

func (i fileType) String() string {
	if i < 0 || i >= fileType(len(_fileType_index)-1) {
		return "fileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _fileType_name[_fileType_index[i]:_fileType_index[i+1]]
}
